server:
  port: 8080

spring:
  application:
    name: main-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_db
    username: postgres
    password: password
    hikari:
      connection-timeout: 10000
      initialization-fail-timeout: -1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

stats:
  server:
    url: ${STATS_SERVER_URL:http://localhost:9090}